schema_version = "1.0.0"

id = "tws_game_tools"
version = "1.3.0"
name = "TWS Game Tools"
tagline = "Blender Addon for Game Assets"
maintainer = "TheWhiteShadow"
type = "add-on"
website = "https://github.com/TheWhiteShadow4/Blender-Game-Tools"

tags = ["Modeling", "Bake", "Import-Export"]

blender_version_min = "4.4.0"
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]